### ISSUE TITLE
잔돈 빼기 기능

### ISSUE THREAD

**Issue by shinsehantan** [jum0/dutch-dutch#15]
카카오페이에서 1/n 정산하기를 하면, 
10원 이하 단위(맞나?)는 카카오페이에서 부담해주기도 하는데요.

뿜빠이를 할 때에도 10원 단위까지 받지는 않으니까
뿜빠이 결과물에서 10원 이하 결과는 빼주는 기능이 있으면 좋을 것 같아요.

[x] 10원 이하 잔돈 빼기
결과 2530원 -> 2500원

**Comment by jum0** [comment]
확인해 보니 5명이서 7원을 나누는 경우 2원이 남는데, 현재 카카오 페이 1원 단위는 부담하고 있다고 하네요!

현재 dutch-dutch 계산 로직은 1원 단위를 무조건 절사하고 있는데, 말씀하신 것처럼 뿜빠이를 할 때 10원 이하의 잔돈은 고려하지 않는 경우도 많아서 [이전에 등록된 이슈](https://github.com/jum0/dutch-dutch/issues/6)에서 같이 고민해 보도록 하겠습니다! 감사합니다!
