### ISSUE TITLE
추가하기 버튼 위치가 입력창 아래에 있으면 좋겠어요.

### ISSUE THREAD

**Issue by shinsehantan** [jum0/dutch-dutch#16]
초기 화면 기준으로는
대칭으로 잘 배치된 화면이 굉장히 자연스럽지만

사람을 1명 추가하려고 할 때 휴대폰 기준으로 스크롤을 다시 끌어내려야 하는 점이 불편했어요.
사람을 바로 추가할 수 있게 하단 입력창과 계산하기 사이에 '추가하기' 버튼이 오면 좋을 것 같아요.
(+ 버튼만 있어도 충분할 것 같아요.)

![KakaoTalk_Photo_2021-12-03-13-57-35](https://user-images.githubusercontent.com/67591151/144549059-be9d950b-5fc8-4c40-8b25-cfe4c12669b9.png)

**Comment by jum0** [comment]
추가 버튼이 안 보이는 것은 생각 못 했네요! 이슈 등록 감사합니다!
