### ISSUE TITLE
금액 숫자에 쉼표가 있으면 좋겠어요

### ISSUE THREAD

**Issue by devhyun637** [jum0/dutch-dutch#18]
더치더치 색이 만원의 색같아서 좋네요~!
더치페이의 금액에 대해서 금액이 클 경우에 가독성을 위해서 쉼표를 넣어보는 건 어떨까요?!

<img width="583" alt="스크린샷 2021-12-03 오후 9 44 20" src="https://user-images.githubusercontent.com/59258239/144604622-189ed322-b5fe-4491-b144-875138eb1341.png">

저같이 눈이 침침한 사람들은 일십백천만..이러면서 읽고 있습니다..ㅎ

**Comment by jum0** [comment]
제안 감사합니다!
