### ISSUE TITLE
모두가 같은 금액을 입력하면 앱이 터져요.

### ISSUE THREAD

**Issue by shinsehantan** [jum0/dutch-dutch#20]
더치페이 하는 사람들이 같은 금액을 입력하고 계산하기를 누르면 앱이 터져요.
인원수는 관련없는 것 같습니다.

<img width="492" alt="스크린샷 2021-12-03 오후 9 58 27" src="https://user-images.githubusercontent.com/67591151/144606523-aca8f9e7-9be8-4cf3-b39e-03485d5a5a9c.png">

**Comment by jum0** [comment]
버그 발견 감사합니다!
