### ISSUE TITLE
입력창 글자 수에 제한을 두면 좋을 것 같아요.

### ISSUE THREAD

**Issue by shinsehantan** [jum0/dutch-dutch#22]
막지 않으면 아래와 같은 일이 발생합니다.

<img width="478" alt="스크린샷 2021-12-03 오후 10 02 45" src="https://user-images.githubusercontent.com/67591151/144607494-37f7f681-2a27-46d9-ae52-ba9d092089ab.png">

**Comment by jum0** [comment]
오... 꼭 고치겠습니다..!
